#!/usr/bin/env python3
"""Plot the recorded MAVROS local position trajectory in 3D."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Optional

import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm
from matplotlib.colors import Normalize
from mpl_toolkits.mplot3d.art3d import Line3DCollection


def _parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    default_dir = Path.home() / "gestelt_ws" / "collected_poses"

    parser = argparse.ArgumentParser(
        description=(
            "Load timestamps.npy and positions.npy generated by "
            "local_position_logger.py and plot the trajectory in 3D."
        )
    )
    parser.add_argument(
        "--directory",
        type=Path,
        default=default_dir,
        help=(
            "Directory containing timestamps.npy and positions.npy (defaults "
            f"to {default_dir})."
        ),
    )
    parser.add_argument(
        "--timestamps",
        type=Path,
        default=None,
        help="Explicit path to timestamps.npy (overrides --directory).",
    )
    parser.add_argument(
        "--positions",
        type=Path,
        default=None,
        help="Explicit path to positions.npy (overrides --directory).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional path to save the rendered figure (e.g. trajectory.png).",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display the plot window in addition to saving (if requested).",
    )
    parser.add_argument(
        "--elev",
        type=float,
        default=25.0,
        help="Matplotlib elevation angle for the 3D view (degrees).",
    )
    parser.add_argument(
        "--azim",
        type=float,
        default=-60.0,
        help="Matplotlib azimuth angle for the 3D view (degrees).",
    )

    return parser.parse_args(argv)


def _resolve_array_path(
    override: Optional[Path], directory: Path, filename: str
) -> Path:
    if override is not None:
        return override
    return directory / filename


def _load_positions(path: Path) -> np.ndarray:
    if not path.exists():
        raise FileNotFoundError(f"Position file not found: {path}")

    positions = np.load(path)
    if positions.ndim != 2 or positions.shape[1] != 3:
        raise ValueError(
            "positions.npy must be a 2-D array with shape (N, 3); "
            f"received array with shape {positions.shape}"
        )
    return positions


def _load_timestamps(path: Path) -> Optional[np.ndarray]:
    if not path.exists():
        return None

    times = np.load(path)
    if times.ndim != 1:
        raise ValueError(
            "timestamps.npy must be a 1-D array of message times; "
            f"received array with shape {times.shape}"
        )
    return times


def _make_trajectory_plot(
    positions: np.ndarray,
    times: Optional[np.ndarray],
    elev: float,
    azim: float,
) -> plt.Figure:
    fig = plt.figure(figsize=(12, 6))
    ax = fig.add_subplot(projection="3d")

    xs, ys, zs = positions.T

    has_time_samples = (
        times is not None
        and times.shape[0] == positions.shape[0]
        and times.size > 0
    )

    if has_time_samples:
        relative_times = times - times[0]
        segments = np.stack((positions[:-1], positions[1:]), axis=1)
        rel_time_min = float(relative_times.min())
        rel_time_max = float(relative_times.max())
        if rel_time_max == rel_time_min:
            rel_time_max = rel_time_min + 1.0
        norm = Normalize(vmin=rel_time_min, vmax=rel_time_max)
        colors = cm.viridis(norm(relative_times[:-1]))
        collection = Line3DCollection(segments, colors=colors, linewidths=2.0)
        ax.add_collection(collection)
        cbar = fig.colorbar(cm.ScalarMappable(norm=norm, cmap="viridis"), ax=ax)
        cbar.set_label("Time [s]")
    else:
        if times is not None and times.shape[0] != positions.shape[0]:
            print(
                "[plot_local_position] Warning: timestamps count does not match "
                "positions; drawing uncolored trajectory."
            )
        ax.plot(xs, ys, zs, linewidth=2.0, color="#1f77b4")

    # Mark start (green) and end (red) points
    ax.scatter(positions[0, 0], positions[0, 1], color='lime', s=60, label='Start', edgecolor='k', zorder=10)
    ax.scatter(positions[-1, 0], positions[-1, 1], color='red', s=60, label='End', edgecolor='k', zorder=10)
    ax.legend(loc="best")

    ax.set_xlabel("X [m]")
    ax.set_ylabel("Y [m]")
    ax.set_zlabel("Z [m]")
    ax.set_title("MAVROS Local Position Trajectory")
    ax.view_init(elev=elev, azim=azim)

    # Equal aspect ratio for XYZ dimensions, with limits derived from
    # min/max bounds and a modest shared margin for visibility.
    mins = positions.min(axis=0)
    maxs = positions.max(axis=0)
    spans = maxs - mins
    max_span = np.max(spans)
    if max_span == 0:
        max_span = 1.0

    margin = 0.12 * max_span  # 12% margin based on the largest axis span
    mins_with_margin = mins - margin
    maxs_with_margin = maxs + margin
    spans_with_margin = maxs_with_margin - mins_with_margin
    target_span = np.max(spans_with_margin)
    half_span = target_span / 2.0
    centers = (mins + maxs) / 2.0

    ax.set_xlim(centers[0] - half_span, centers[0] + half_span)
    ax.set_ylim(centers[1] - half_span, centers[1] + half_span)

    z_lower_bound = mins[2] - margin
    if mins[2] >= 0:
        z_lower_bound = max(z_lower_bound, 0.0)
    z_lower = max(centers[2] - half_span, z_lower_bound)
    z_upper = z_lower + target_span
    ax.set_zlim(z_lower, z_upper)

    return fig


def _make_xyz_time_plot(
    positions: np.ndarray,
    times: Optional[np.ndarray],
    output: Optional[Path] = None,
    show: bool = False,
):
    if times is None or times.shape[0] != positions.shape[0]:
        print("[plot_local_position] Skipping XYZ vs time plot (timestamps missing or mismatched).")
        return

    if times.size == 0:
        print("[plot_local_position] Skipping XYZ vs time plot (no timestamp samples available).")
        return

    relative_times = times - times[0]

    fig, axes = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
    labels = ['X [m]', 'Y [m]', 'Z [m]']
    for i, ax in enumerate(axes):
        ax.plot(relative_times, positions[:, i], label=labels[i])
        ax.set_ylabel(labels[i])
        ax.grid(True)
        ax.legend(loc='best')
    axes[-1].set_xlabel('Time [s]')
    fig.suptitle('X, Y, Z Position vs Time')

    if output is not None:
        out_path = output.parent / (output.stem + "_xyz_vs_time.png")
        fig.savefig(out_path, bbox_inches="tight", dpi=600)
        print(f"Saved X/Y/Z vs Time plot to {out_path}")

    if show:
        plt.show()
    else:
        plt.close(fig)


def _make_xy_plot(
    positions: np.ndarray,
    times: Optional[np.ndarray],
    output: Optional[Path] = None,
    show: bool = False,
):
    fig, ax = plt.subplots(figsize=(7, 7))
    if times is not None and times.shape[0] == positions.shape[0]:
        sc = ax.scatter(positions[:, 0], positions[:, 1], c=times, cmap="viridis", s=8)
        cbar = fig.colorbar(sc, ax=ax)
        cbar.set_label("Time [s]")
    else:
        ax.plot(positions[:, 0], positions[:, 1], label="Trajectory")
        ax.legend(loc="best")
    ax.set_xlabel("X [m]")
    ax.set_ylabel("Y [m]")
    ax.set_title("XY Trajectory Projection")
    ax.axis("equal")
    ax.grid(True)

    # Mark start (green) and end (red) points
    ax.scatter(positions[0, 0], positions[0, 1], color='lime', s=60, label='Start', edgecolor='k', zorder=10)
    ax.scatter(positions[-1, 0], positions[-1, 1], color='red', s=60, label='End', edgecolor='k', zorder=10)
    ax.legend(loc="best")

    if output is not None:
        out_path = output.parent / (output.stem + "_xy.png")
        fig.savefig(out_path, bbox_inches="tight", dpi=600)
        print(f"Saved XY plot to {out_path}")

    if show:
        plt.show()
    else:
        plt.close(fig)


def main(argv: Optional[list[str]] = None) -> None:
    args = _parse_args(argv)

    positions_path = _resolve_array_path(args.positions, args.directory, "positions.npy")
    timestamps_path = _resolve_array_path(
        args.timestamps, args.directory, "timestamps.npy"
    )

    positions = _load_positions(positions_path)
    times = None
    try:
        times = _load_timestamps(timestamps_path)
    except ValueError as exc:
        print(f"[plot_local_position] {exc}")

    fig = _make_trajectory_plot(positions, times, args.elev, args.azim)

    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(args.output, bbox_inches="tight", dpi=600)
        print(f"Saved 3D trajectory plot to {args.output}")

    # --- Add this call to generate the XYZ vs time plot ---
    _make_xyz_time_plot(positions, times, args.output, args.show)
    _make_xy_plot(positions, times, args.output, args.show)

    if args.show:
        plt.show()
    else:
        plt.close(fig)


if __name__ == "__main__":
    main()
